name: DependaBot Metrics

on:
  schedule:
    - cron: '28 23 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.COLLECT_ANALYCTS }}
      ORGANIZATION: ${{ secrets.ORGANIZATION }}
      WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          cpanm --installdeps .
      
      - name: Run DependaBot metrics and send to Slack
        run: |
          message=$(perl sentra.pl -o $ORGANIZATION -t $TOKEN)
          perl sentra.pl -w $WEBHOOK -m "$message"
