name: Search for DependaBot files

on:
  schedule:
    - cron: '28 23 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.READ_CONTENT }}
      ORGANIZATION: ${{ secrets.ORGANIZATION }}
      WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          cpanm --installdeps .
      
      - name: Search for DependaBot files and send to Slack
        run: |
          message=$(perl sentra.pl -o $ORGANIZATION -t $TOKEN --dependency)
          perl sentra.pl -w $WEBHOOK -m "$message"
